### PR TITLE
Preliminary support for Pixel 4

### PR DESCRIPTION
**Pull request by nickrbogdanov**
Not sure if all of the drivers work correctly, but the device can boot to the home screen and run Chromium and OpenCamera.  Wifi and LTE data seem sane.

### CODE REVIEW

**Comment by dan-v** [comment]
Thanks for the PR @nickrbogdanov! If you have time, could you poke around and compare the other work from hashbang os and calyxos: https://github.com/chirayudesai/android-prepare-vendor/commits/coral-flame as it was just recently confirmed booting there as well. I'll likely pull in the changes from @chirayudesai as I like to try to keep android-prepare-vendor in sync across these other projects. @chirayudesai - is everything working ok on flame/coral as far as you can tell and do you plan on pulling these changes into your q branch?

**Comment by chirayudesai** [comment]
I hadn't seen this at all. We do really need to keep them all in one place :)

It does boot, and from a quick check everything does work.
Wi-Fi, BT, Mobile data, Camera and so on.
Face Unlock works too!

I had an issue with a VoLTE call but I didn't delve deeper / try another SIM.

**Comment by nickrbogdanov** [comment]
Thanks, looks like this is much farther along than my attempt.

I updated my branch to use @chirayudesai's `config.json` as a baseline, with a few additional commits.  Unfortunately this doesn't boot for me, need to rebuild as -eng to debug it.  Was the flame configuration tested yet?

**Comment by dan-v** [comment]
@nickrbogdanov - thanks for taking and look and pulling in the other branch. It's super helpful to have someone with a Pixel 4 (I don't have one) and knowledge to work through issues. Doing a debug build is a good idea. It sounds like you at least had a working configuration previously, so could be a bit of diffing between the two configs and some painful trial and error testing. 

@chirayudesai - can you confirm what device you validated your branch on? Also are there any other changes outside of what's on your branch?

**Comment by chirayudesai** [comment]
@nickrbogdanov @dan-v  I can confirm that both coral and flame boot for me with my android-prepare-vendor

I had to make a small change to build/soong to temporarily remove `--werror_overriding_commands`, but that was a build time issue and not runtime.

You can check device/kernel at https://gitlab.com/calyxos - We build the kernel inline now but I tested with google's prebuilt kernel first and that was fine.

**Comment by chirayudesai** [comment]
@nickrbogdanov that's it, I forgot that I removed the ims package locally in the generated files because of missing permissions.

**Comment by nickrbogdanov** [comment]
> I had to make a small change to build/soong to temporarily remove --werror_overriding_commands, but that was a build time issue and not runtime.

For now I'm also doing:

```
From 5093afd2b1e6aa1b1492e3594f471ec2cd222bc3 Mon Sep 17 00:00:00 2001
From: unknown <unknown@localhost>
Date: Sun, 19 Apr 2020 22:51:03 +0000
Subject: [PATCH] HACK: Enable BUILD_BROKEN_DUP_RULES for coral/flame

Signed-off-by: unknown <unknown@localhost>
Change-Id: Ia2a13fe89b300960aa66f48da43e7ea092f5a739
---
 BoardConfig-common.mk | 1 +
 1 file changed, 1 insertion(+)

diff --git a/BoardConfig-common.mk b/BoardConfig-common.mk
index c615f58..16677ef 100644
--- a/BoardConfig-common.mk
+++ b/BoardConfig-common.mk
@@ -35,6 +35,7 @@ TARGET_2ND_CPU_VARIANT := generic
 TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a76
 
 BUILD_BROKEN_ENG_DEBUG_TAGS := true
+BUILD_BROKEN_DUP_RULES := true
 
 TARGET_BOARD_COMMON_PATH := device/google/coral/sm8150
 
-- 
2.17.1
```

It looks like earlier Pixel phones enabled this workaround but coral/flame AOSP is shipping "clean" so we have to manually re-enable it to use a-p-v.  Need to find a way to definitively list all of the duplicated rules and then add them as exclusions in config.json.  But right now getting the phone to boot at all is my top priority.

**Comment by chirayudesai** [comment]
Ah, I hadn't realised BUILD_BROKEN_DUP_RULES was set in the devices. That's what `--werror_overriding_commands` does.

We can definitely figure out the duplicates programatically, just make these errors into warnings, get a list and then exclude those.

Does it still not boot for you? If you're on freenode IRC, I'm cdesai on #calyxos, feel free to drop by.

**Comment by nickrbogdanov** [comment]
New problem, now that the others have been resolved.  Does this look familiar to anyone?

```
04-28 08:41:06.772  5076  5076 I QtiTelephonyService: onCreate:
04-28 08:41:06.772  5076  5076 D AndroidRuntime: Shutting down VM
04-28 08:41:06.773  5076  5076 E AndroidRuntime: FATAL EXCEPTION: main
04-28 08:41:06.773  5076  5076 E AndroidRuntime: Process: com.qualcomm.qti.telephonyservice, PID: 5076
04-28 08:41:06.773  5076  5076 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qualcomm/qcrilhook/QcRilHook;
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at com.qualcomm.qti.telephonyservice.QtiTelephonyService.onCreate(QtiTelephonyService.java:58)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-28 08:41:06.773  5076  5076 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qualcomm.qcrilhook.QcRilHook
04-28 08:41:06.773  5076  5076 E AndroidRuntime: 	... 10 more
04-28 08:41:06.775  1312  2134 V RescueParty: Disabled because of eng build
04-28 08:41:06.776  1312  2134 W ActivityManager: Process com.qualcomm.qti.telephonyservice has crashed too many times: killing!
04-28 08:41:06.779  5076  5076 I Process : Sending signal. PID: 5076 SIG: 9
04-28 08:41:06.784  1312  1329 I ActivityManager: Process com.qualcomm.qti.telephonyservice (pid 5076) has died: pers PER 
04-28 08:41:06.784   705   705 I Zygote  : Process 5076 exited due to signal 9 (Killed)
```

The .jar file is there:

```
flame:/ # find /system /vendor /product | grep -i qcril
/vendor/lib64/libqcrilFramework.so
/vendor/lib64/libqcrildatactl.so
/vendor/lib64/libril-qcril-hook-oem.so
/vendor/lib64/qcrild_librilutils.so
/vendor/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so
/vendor/lib/libqcrilFramework.so
/vendor/lib/libqcrildatactl.so
/vendor/lib/libril-qcril-hook-oem.so
/vendor/lib/qcrild_librilutils.so
/vendor/lib/vendor.qti.hardware.radio.qcrilhook@1.0.so
/vendor/radio/qcril_database
/vendor/radio/qcril_database/qcril.db
/vendor/radio/qcril_database/upgrade
/vendor/radio/qcril_database/upgrade/1_version_intro.sql
/vendor/radio/qcril_database/upgrade/9_taiwan_ecc_110_and_119.sql
/vendor/radio/qcril_database/upgrade/0_initial.sql
/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql
/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql
/vendor/radio/qcril_database/upgrade/6_singapore_ecc_995.sql
/vendor/radio/qcril_database/upgrade/5_version_google_feature.sql
/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql
/vendor/radio/qcril_database/upgrade/8_USCC_update_ecc_table.sql
/vendor/radio/qcril_database/upgrade/7_remove_germany_hard_ecc_110.sql
/vendor/etc/init/qcrild.rc
/vendor/bin/hw/qcrild
/product/framework/qcrilhook.jar
/product/priv-app/qcrilmsgtunnel
/product/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk
/product/etc/permissions/qcrilhook.xml
/product/etc/permissions/com.qualcomm.qcrilmsgtunnel.xml
```

Running apktool on QtiTelephonyService shows that it has a `uses-library` node for the library in question:

```
    <application android:directBootAware="true" android:extractNativeLibs="false" android:persistent="true" android:usesNonSdkApi="true">
        <uses-library android:name="com.qualcomm.qcrilhook"/>
        <uses-library android:name="qti-telephony-hidl-wrapper"/>
        <uses-library android:name="qti-telephony-utils"/>
        <receiver android:enabled="true" android:exported="false" android:label="BootReceiver" android:name=".BootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.LOCKED_BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
        <service android:enabled="true" android:exported="true" android:name=".QtiTelephonyService" android:permission="com.qualcomm.qti.permission.USE_QTI_TELEPHONY_SERVICE">
            <intent-filter>
                <action android:name="com.qualcomm.qti.telephonyservice.IQtiTelephonyService"/>
            </intent-filter>
        </service>
    </application>
```

So I guess we need to figure out why ART isn't finding that library.  There's probably some way to tell it to spit out more diagnostic info but I haven't found the incantation yet.

Also, `setenforce 0` doesn't help.

**Comment by chirayudesai** [comment]
@nickrbogdanov so I pulled in the commits you made, and flame boots just fine here on CalyxOS!

IMS works too, just tested.

**Comment by nickrbogdanov** [comment]
@chirayudesai You're not seeing the endless crashes in the background?

My Pixel 4 running AOSP with this a-p-v branch "looks" normal (other than phone stuff not working) but if you watch logcat it's constantly crashing and restarting the Qualcomm stuff. It's warm to the touch and the battery drains very quickly.

**Comment by chirayudesai** [comment]
@nickrbogdanov nope, working just fine here.

Calls, texts and mobile data works. I've left it on to see what battery drain looks like.

**Comment by dan-v** [comment]
@nickrbogdanov - just wanted to give you a heads up, i made some changes on the dev branch here (https://github.com/RattlesnakeOS/android-prepare-vendor/commit/57dd39177d19c365d57e19ed33417dd0034d9378) that appear to make things happy. @chirayudesai was kind enough to test the coral image i built and it appears to boot and call.

**Comment by dan-v** [comment]
Closing this as pixel 4 changes are now in 10.0 branch.

**Pull request closed without merging**
